<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Assets\ExtraTextures\SolarBladeGlowMask\**" />
	  <Compile Remove="Assets\ExtraTextures\SolarBladeGlowMask\**" />
	  <EmbeddedResource Remove="Assets\ExtraTextures\SolarBladeGlowMask\**" />
	  <None Remove="Assets\ExtraTextures\SolarBladeGlowMask\**" />
	</ItemGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Assets\Effects\Overlays\EdgeMeltsShader.fx" />
	  <AdditionalFiles Remove="Assets\Effects\Overlays\TerraRayVinesShader.fx" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="CalamityMod">
	    <HintPath>..\..\ModReader\CalamityMod\CalamityMod.dll</HintPath>
	  </Reference>
	  <Reference Include="LAP">
	    <HintPath>..\LAP\bin\Debug\net8.0\LAP.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<ItemGroup>
	  <EditorConfigFiles Remove="C:\Users\Administrator\Documents\My Games\Terraria\tModLoader\ModSources\UCA\.editorconfig" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="C:\Users\Administrator\Documents\My Games\Terraria\tModLoader\ModSources\UCA\.editorconfig" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Content\ItemOverride\Magic\" />
	</ItemGroup>

	<!-- References -->

</Project>